apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: random-strings
spec:
  steps:
    - name: random-strings
      image: busybox:1.36.1-uclibc
      command: ["/bin/sh", "-c"]
      args:
        - for i in $(seq 1 100); do cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 80; echo; done
